# Generated by Django 5.1.5 on 2025-02-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
    ]
