# Generated by Django 5.1.5 on 2025-02-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20250213_2257'),
    ]

    operations = [
    ]
